/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tickets.vista;

/**
 *
 * @author SARA/tomy
 */
public class ClienteVista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteVista.class.getName());

    /**
     * Creates new form ClienteVista
     */
    public ClienteVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asientosOp = new javax.swing.ButtonGroup();
        nombre = new javax.swing.JLabel();
        nombreIn = new javax.swing.JTextField();
        documento = new javax.swing.JLabel();
        documentoIn = new javax.swing.JTextField();
        artista = new javax.swing.JLabel();
        localidad = new javax.swing.JLabel();
        localidadA = new javax.swing.JRadioButton();
        sitsA = new javax.swing.JLabel();
        localidadB = new javax.swing.JRadioButton();
        sitsB = new javax.swing.JLabel();
        localidadC = new javax.swing.JRadioButton();
        localidadD = new javax.swing.JRadioButton();
        sitsC = new javax.swing.JLabel();
        sitsD = new javax.swing.JLabel();
        boletosCant = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        boletosBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        richieRay = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        nombre.setText("Nombre: ");

        nombreIn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        documento.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        documento.setText("Documento: ");

        artista.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        artista.setText("Artista");

        localidad.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        localidad.setText("Localidad");

        asientosOp.add(localidadA);
        localidadA.setText("A");

        sitsA.setText("(101-111)");

        asientosOp.add(localidadB);
        localidadB.setText("B");

        sitsB.setText("(201-222)");

        asientosOp.add(localidadC);
        localidadC.setText("C");

        asientosOp.add(localidadD);
        localidadD.setText("D");

        sitsC.setText("(303-333)");

        sitsD.setText("(404-444)");

        boletosCant.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        boletosCant.setText("Cantidad de boletos");

        registrar.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        registrar.setText("Registrar");

        boletosBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel1.setText("Ingresar datos");

        richieRay.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        richieRay.setText("Richie Ray 32/02/2222");

        modificar.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        modificar.setText("Modificar");

        eliminar.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        eliminar.setText("Eliminar");

        buscar.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        buscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(documento)
                                .addComponent(nombre)
                                .addComponent(artista)
                                .addComponent(localidad))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreIn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(documentoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(localidadD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(sitsD))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(localidadC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sitsC))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(localidadB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sitsB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(localidadA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sitsA)))
                                .addComponent(richieRay)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(boletosCant)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boletosBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registrar)
                        .addGap(18, 18, 18)
                        .addComponent(modificar)
                        .addGap(18, 18, 18)
                        .addComponent(eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(buscar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artista)
                    .addComponent(richieRay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidad)
                    .addComponent(localidadA)
                    .addComponent(sitsA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidadB)
                    .addComponent(sitsB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidadC)
                    .addComponent(sitsC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidadD)
                    .addComponent(sitsD))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boletosCant)
                    .addComponent(boletosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar)
                    .addComponent(modificar)
                    .addComponent(eliminar)
                    .addComponent(buscar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel artista;
    public javax.swing.ButtonGroup asientosOp;
    public javax.swing.JComboBox<String> boletosBox;
    public javax.swing.JLabel boletosCant;
    public javax.swing.JButton buscar;
    public javax.swing.JLabel documento;
    public javax.swing.JTextField documentoIn;
    public javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel localidad;
    public javax.swing.JRadioButton localidadA;
    public javax.swing.JRadioButton localidadB;
    public javax.swing.JRadioButton localidadC;
    public javax.swing.JRadioButton localidadD;
    public javax.swing.JButton modificar;
    public javax.swing.JLabel nombre;
    public javax.swing.JTextField nombreIn;
    public javax.swing.JButton registrar;
    public javax.swing.JLabel richieRay;
    public javax.swing.JLabel sitsA;
    public javax.swing.JLabel sitsB;
    public javax.swing.JLabel sitsC;
    public javax.swing.JLabel sitsD;
    // End of variables declaration//GEN-END:variables
}
